In [58]:
import torch
import torch.nn as nn

In [59]:
X = torch.tensor([
    [3.0,  4.0,  2.0],
    [2.0,  3.5,  3.0],
    [4.0,  4.5,  1.0],
    [1.5,  3.0,  2.0],
    [5.0,  3.8,  3.0],
    [8.0,  7.5,  0.0],
    [10.0, 8.0,  1.0],
    [7.0,  7.0,  0.0],
    [12.0, 9.0,  0.0],
    [6.0,  7.2,  1.0],
], dtype=torch.float32)

Y = torch.tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
                 dtype=torch.float32).reshape(-1, 1)

Y.shape

torch.Size([10, 1])

In [60]:
_ = torch.manual_seed(42)

model = nn.Sequential(
    nn.Linear(3, 5),
    nn.ReLU(),
    nn.Linear(5, 1),
    nn.Sigmoid()
)

model

Sequential(
  (0): Linear(in_features=3, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
  (3): Sigmoid()
)

In [76]:
model[0]
model[1]
model[2]
model[3]

Linear(in_features=3, out_features=5, bias=True)

ReLU()

Linear(in_features=5, out_features=1, bias=True)

Sigmoid()

In [85]:
model[0].weight.shape  # W
model[0].weight.grad.shape  # dW

model[0].bias.shape  # b
model[0].bias.grad.shape  # db

torch.Size([5, 3])

torch.Size([5, 3])

torch.Size([5])

torch.Size([5])

In [61]:
for param in model.parameters():
  param

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353],
        [ 0.5304, -0.1265,  0.1165],
        [-0.2811,  0.3391,  0.5090],
        [-0.4236,  0.5018,  0.1081],
        [ 0.4266,  0.0782,  0.2784]], requires_grad=True)

Parameter containing:
tensor([-0.0815,  0.4451,  0.0853, -0.2695,  0.1472], requires_grad=True)

Parameter containing:
tensor([[-0.2060, -0.0524, -0.1816,  0.2967, -0.3530]], requires_grad=True)

Parameter containing:
tensor([-0.2062], requires_grad=True)

In [72]:
for name, param in model.named_parameters():
  print(f'{name}')
  print(f'{param.shape}\n')

0.weight
torch.Size([5, 3])

0.bias
torch.Size([5])

2.weight
torch.Size([1, 5])

2.bias
torch.Size([1])



In [62]:
for key, val in model.state_dict().items():
  print(f'{key}')
  print(f'{val}\n')

0.weight
tensor([[ 0.4414,  0.4792, -0.1353],
        [ 0.5304, -0.1265,  0.1165],
        [-0.2811,  0.3391,  0.5090],
        [-0.4236,  0.5018,  0.1081],
        [ 0.4266,  0.0782,  0.2784]])

0.bias
tensor([-0.0815,  0.4451,  0.0853, -0.2695,  0.1472])

2.weight
tensor([[-0.2060, -0.0524, -0.1816,  0.2967, -0.3530]])

2.bias
tensor([-0.2062])



In [63]:
loss_fn = nn.BCELoss()
loss_fn

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
optimizer

BCELoss()

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [64]:
with torch.inference_mode():
  Y_pred = (model(X) > 0.5).type(torch.int)

(Y_pred == Y).sum() / len(Y)

tensor(0.5000)

In [65]:
epochs = 1000

for epoch in range(1, epochs+1):
  output = model(X)
  loss = loss_fn(output, Y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 100 == 0 or epoch == 1:
    print(f"  Epoch {epoch:>4} | Loss: {loss.item():.4f}")

  Epoch    1 | Loss: 1.8763
  Epoch  100 | Loss: 0.0820


  Epoch  200 | Loss: 0.0538
  Epoch  300 | Loss: 0.0383
  Epoch  400 | Loss: 0.0281
  Epoch  500 | Loss: 0.0213
  Epoch  600 | Loss: 0.0166
  Epoch  700 | Loss: 0.0134
  Epoch  800 | Loss: 0.0110
  Epoch  900 | Loss: 0.0092
  Epoch 1000 | Loss: 0.0078


In [66]:
with torch.inference_mode():
  Y_pred = (model(X) > 0.5).type(torch.int)

(Y_pred == Y).sum() / len(Y)

tensor(1.)

In [67]:
print("\nUnseen Applicants:")
X = torch.tensor([
    [9.0,  8.5,  0.0],
    [2.5,  3.2,  4.0],
    [6.5,  7.0,  1.0],
], dtype=torch.float32)
Y = torch.tensor([1, 0, 1], dtype=torch.float32).reshape(-1, 1)

with torch.inference_mode():
  Y_pred = (model(X) > 0.5).type(torch.int)

(Y_pred == Y).sum() / len(Y)


Unseen Applicants:


tensor(1.)