In [2]:
import torch
import numpy as np
torch.__version__

'2.4.1+cpu'

## 0D Tensor (Scalar)

In [3]:
torch.tensor(3)
torch.tensor(3).item()

tensor(3)

3

In [4]:
scalar = torch.tensor(2)
scalar.dim()
scalar.ndim

0

0

In [5]:
scalar.shape
scalar.size()

torch.Size([])

torch.Size([])

In [6]:
scalar.dtype

torch.int64

## 1D Tensor (vector)

In [7]:
vector = torch.tensor([2, 3, 5])
vector

tensor([2, 3, 5])

In [8]:
vector.dim()
vector.ndim

1

1

In [9]:
vector.shape
vector.dtype

torch.Size([3])

torch.int64

In [10]:
len(vector)
vector.numel()

3

3

In [11]:
vector.sum()
vector.float().sum()

tensor(10)

tensor(10.)

In [12]:
# L2 norm (Euclidean length)
vector.float().norm()
(vector**2)
(vector**2).sum()
(vector**2).sum().sqrt()

tensor(6.1644)

tensor([ 4,  9, 25])

tensor(38)

tensor(6.1644)

## 2D Tensor (Matrix)

In [13]:
matrix = torch.tensor([
    [2, 3],
    [6, 7]
])

matrix
matrix.shape
matrix.dim()

tensor([[2, 3],
        [6, 7]])

torch.Size([2, 2])

2

In [47]:
len(matrix)  # no of rows
matrix.numel()  # no of elems

2

4

In [15]:
matrix.float()
matrix.float().det()

tensor([[2., 3.],
        [6., 7.]])

tensor(-4.0000)

In [16]:
matrix.trace()
matrix.float()
matrix.float().norm()

tensor(9)

tensor([[2., 3.],
        [6., 7.]])

tensor(9.8995)

## Higher-Order Tensors (Rank ≥ 3)

In [17]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

tensor.ndim
tensor.shape

3

torch.Size([1, 3, 3])

## Useful Tensor Initializations

In [18]:
torch.zeros(size=(2, 2))
torch.ones(size=(2, 2))
torch.eye(2)

tensor([[0., 0.],
        [0., 0.]])

tensor([[1., 1.],
        [1., 1.]])

tensor([[1., 0.],
        [0., 1.]])

In [19]:
torch.rand(size=(2, 2))
torch.randint(1, 5, size=(2, 10))

tensor([[0.2022, 0.8065],
        [0.8503, 0.0729]])

tensor([[2, 2, 3, 3, 1, 2, 4, 2, 3, 1],
        [4, 3, 3, 2, 1, 3, 2, 3, 2, 2]])

In [20]:
torch.arange(1, 10, 2)
torch.linspace(4, 10, 5)

tensor([1, 3, 5, 7, 9])

tensor([ 4.0000,  5.5000,  7.0000,  8.5000, 10.0000])

In [21]:
torch.zeros_like(matrix)

tensor([[0, 0],
        [0, 0]])

## Tensor datatypes

In [22]:
torch.tensor([2, 3, 4]).dtype
torch.tensor([2, 3, 4], dtype=torch.float).dtype
torch.tensor([2, 3, 4], dtype=torch.float32).dtype
torch.tensor([2, 3, 4], dtype=torch.float64).dtype
torch.tensor([2, 3, 4], dtype=torch.float16).dtype

torch.int64

torch.float32

torch.float32

torch.float64

torch.float16

In [23]:
torch.tensor([2.2, 3.3, 4.4]).dtype
torch.tensor([2.2, 3.3, 4.4], dtype=torch.int).dtype
torch.tensor([2.2, 3.3, 4.4], dtype=torch.int32).dtype
torch.tensor([2.2, 3.3, 4.4], dtype=torch.int16).dtype

torch.float32

torch.int32

torch.int32

torch.int16

In [48]:
tensor = torch.tensor([3, 4, 5], dtype=torch.float64)
tensor.element_size()  # how many bytes per elem

tensor = torch.tensor([3, 4, 5], dtype=torch.float16)
tensor.element_size()

tensor = torch.tensor([3, 4, 5], dtype=torch.float32)
tensor.element_size()

8

2

4

In [25]:
tensor = torch.tensor([3, 4, 5])
tensor.dtype

tensor.type(torch.float)
tensor.float()

torch.int64

tensor([3., 4., 5.])

tensor([3., 4., 5.])

## Basic operations (broadcasting)

In [26]:
tensor = torch.tensor([450, 50, 65])
tensor + 10
tensor - 10
tensor / 10
tensor // 10

tensor([460,  60,  75])

tensor([440,  40,  55])

tensor([45.0000,  5.0000,  6.5000])

tensor([45,  5,  6])

In [27]:
tensor % 2
tensor % 2 == 0

tensor([0, 0, 1])

tensor([ True,  True, False])

In [28]:
tensor * 2
tensor ** 2
tensor.sqrt()

tensor([900, 100, 130])

tensor([202500,   2500,   4225])

tensor([21.2132,  7.0711,  8.0623])

In [29]:
torch.tensor([10, 20, 50]) + torch.tensor([1, 6, 5])
torch.tensor([10, 20, 50]) / torch.tensor([1, 6, 5])
torch.tensor([10, 20, 50]) * torch.tensor([1, 6, 5])
torch.tensor([10, 20, 50]) - torch.tensor([1, 6, 5])

tensor([11, 26, 55])

tensor([10.0000,  3.3333, 10.0000])

tensor([ 10, 120, 250])

tensor([ 9, 14, 45])

In [30]:
tensor = torch.tensor([9, 4, 5, 6], dtype=torch.float32)
tensor
tensor.dtype

tensor([9., 4., 5., 6.])

torch.float32

In [31]:
tensor.min()
tensor.max()
tensor.sum()

tensor(4.)

tensor(9.)

tensor(24.)

In [32]:
tensor.mean()
tensor.var()
tensor.std()

tensor(6.)

tensor(4.6667)

tensor(2.1602)

In [33]:
tensor
tensor.argmax()
tensor.argmin()

tensor([9., 4., 5., 6.])

tensor(0)

tensor(1)

## Matrix Multiplication

In [34]:
tensor = torch.tensor([3, 4, 5])
tensor
torch.matmul(tensor, tensor)  # 3*3 + 4*4 + 5*5 = 50

tensor([3, 4, 5])

tensor(50)

In [49]:
tensor @ tensor  # dot product

tensor(50.)

In [36]:
tensor1 = torch.tensor([
    [4, 5, 1],
    [6, 7, 8]
])

tensor2 = torch.tensor([
    [0, 0, 0, 2, 1],
    [0, 0, 0, 2, 1],
    [0, 0, 0, 2, 1],
])

tensor1.matmul(tensor2)

tensor([[ 0,  0,  0, 20, 10],
        [ 0,  0,  0, 42, 21]])

## Tensor Reshaping and Dimensionality Operations

In [37]:
x = torch.arange(1, 13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**1. Reshape**

In [38]:
x_reshaped = x.reshape(4, 3)
x_reshaped
x_reshaped.shape

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

torch.Size([4, 3])

**2. View**

In [39]:
z = x.view(2, 6)

z[:, 0] = 99
z
x

tensor([[99,  2,  3,  4,  5,  6],
        [99,  8,  9, 10, 11, 12]])

tensor([99,  2,  3,  4,  5,  6, 99,  8,  9, 10, 11, 12])

**3. Squeeze**

In [ ]:
x_complex = x.reshape(1, 1, 12)
x_complex
print(f'Original Shape: {x_complex.shape}')

x_squeezed = x_complex.squeeze()
x_squeezed
print(f'Squeezed Shape: {x_squeezed.shape}') # one dimension

tensor([[[99,  2,  3,  4,  5,  6, 99,  8,  9, 10, 11, 12]]])

Original Shape: torch.Size([1, 1, 12])


tensor([99,  2,  3,  4,  5,  6, 99,  8,  9, 10, 11, 12])

Squeezed Shape: torch.Size([12])


**4. Unsqueeze**

In [51]:
x_squeezed.shape
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed
print(f'Unsqueezed at dim 0: {x_unsqueezed.shape}')  # two dimension

torch.Size([12])

tensor([[99,  2,  3,  4,  5,  6, 99,  8,  9, 10, 11, 12]])

Unsqueezed at dim 0: torch.Size([1, 12])


In [ ]:
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
print(f'Unsqueezed at dim 1: {x_unsqueezed_1.shape}') # two dimension

Unsqueezed at dim 1: torch.Size([12, 1])


**5. Permute**

In [43]:
x_img = torch.rand(size=(224, 2, 200))
x_permuted = x_img.permute(2, 0, 1)
print(f'Original shape: {x_img.shape}')
print(f'Permuted shape: {x_permuted.shape}')

Original shape: torch.Size([224, 2, 200])
Permuted shape: torch.Size([200, 224, 2])


**6. Stack**

In [58]:
x = torch.arange(1, 6)
x

tensor([1, 2, 3, 4, 5])

In [59]:
h_stack = torch.stack([x, x, x], dim=1)  # dim=0 horizontal direction
h_stack
h_stack.shape

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])

torch.Size([5, 3])

In [60]:
v_stack = torch.stack([x, x, x], dim=0)  # dim=0 downward direction
v_stack
v_stack.shape

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

torch.Size([3, 5])

## Indexing

In [67]:
tensor = torch.tensor([
    [2, 3, 4],
    [5, 6, 7],
    [6, 7, 8]
])

tensor[0]
tensor[0][0]
tensor[0, 0]

tensor([2, 3, 4])

tensor(2)

tensor(2)

In [70]:
tensor[:2]
tensor[:, 0]

tensor([[2, 3, 4],
        [5, 6, 7]])

tensor([2, 5, 6])

In [75]:
tensor[:, :2]
tensor[:2, [0, 1]]
tensor[[0, 2], -1]

tensor([[2, 3],
        [5, 6],
        [6, 7]])

tensor([[2, 3],
        [5, 6]])

tensor([4, 8])

In [78]:
tensor[-1, :]
tensor[-1, -1]

tensor([6, 7, 8])

tensor(8)

## PyTorch Tensors & NumPy

In [82]:
arr = np.array([1, 2, 3])
tensor = torch.from_numpy(arr)
tensor

tensor([1, 2, 3])

In [84]:
tensor.numpy()

array([1, 2, 3])

## Random seed


In [93]:
torch.randint(1, 10, size=(10,))

tensor([4, 5, 7, 7, 1, 6, 7, 4, 6, 6])

In [96]:
torch.manual_seed(42)
torch.randint(1, 10, size=(10,))

tensor([7, 6, 8, 5, 1, 3, 8, 6, 5, 3])

## Getting PyTorch to run on the GPU

In [97]:
torch.cuda.is_available()

False

**💀 CUDA is only for NVIDIA devices**

For AMD GPU we have to use PyTorch with DirectML

DirectML is a low-level hardware abstraction layer that enables you to run machine learning workloads on any DirectX 12 compatible GPU.

In [99]:
import torch_directml

torch_directml.is_available()

True

In [105]:
dml_device = torch_directml.device()
dml_device

device(type='privateuseone', index=0)

In [109]:
cpu_tensor = torch.tensor([1, 2, 3])
gpu_tensor = cpu_tensor.to(dml_device)

In [112]:
result = gpu_tensor + gpu_tensor
result

tensor([2, 4, 6], device='privateuseone:0')

In [115]:
result.device
cpu_tensor.device

device(type='privateuseone', index=0)

device(type='cpu')

In [119]:
torch_directml.device_count()
torch_directml.default_device()

2

0

In [122]:
print(torch_directml.device_name(0))
print(torch_directml.device_name(1))

AMD Radeon RX 6550M
AMD Radeon(TM) 660M


In [124]:
torch.tensor([1, 2, 3, 4], device=dml_device)

tensor([1, 2, 3, 4], device='privateuseone:0')